# Generated by Django 3.1 on 2020-08-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bazaar_app', '0006_auto_20200819_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='MovieRating',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='rating',
        ),
        migrations.CreateModel(
            name='ActorRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='')),
                ('rate', models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_bazaar_app.actor')),
            ],
        ),
    ]
