# Generated by Django 3.1 on 2020-08-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bazaar_app', '0007_auto_20200819_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Inne'), (6, 'Katastroficzny'), (7, 'Animowany'), (1, 'Horror'), (5, 'Akcja'), (4, 'Dramat'), (2, 'Komedia'), (8, 'Kryminalny'), (3, 'Sci-fi')], null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
