# Generated by Django 3.1 on 2020-08-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bazaar_app', '0008_auto_20200819_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(choices=[(3, 'Sci-fi'), (4, 'Dramat'), (6, 'Katastroficzny'), (7, 'Animowany'), (2, 'Komedia'), (5, 'Akcja'), (8, 'Kryminalny'), (1, 'Horror'), (0, 'Inne')], null=True),
        ),
    ]
