# Generated by Django 3.1 on 2020-08-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bazaar_app', '0010_auto_20200820_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Horror'), (7, 'Animowany'), (8, 'Kryminalny'), (6, 'Katastroficzny'), (2, 'Komedia'), (5, 'Akcja'), (3, 'Sci-fi'), (4, 'Dramat'), (0, 'Inne')], null=True),
        ),
    ]
