# Generated by Django 3.1 on 2020-08-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bazaar_app', '0011_auto_20200820_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierating',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_bazaar_app.movierating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Horror'), (2, 'Komedia'), (4, 'Dramat'), (3, 'Sci-fi'), (0, 'Inne'), (5, 'Akcja'), (6, 'Katastroficzny'), (7, 'Animowany'), (8, 'Kryminalny')], null=True),
        ),
    ]
