# Generated by Django 3.1 on 2020-08-22 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bazaar_app', '0012_auto_20200822_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rate',
        ),
        migrations.AddField(
            model_name='movierating',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_bazaar_app.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(choices=[(5, 'Akcja'), (1, 'Horror'), (6, 'Katastroficzny'), (7, 'Animowany'), (8, 'Kryminalny'), (3, 'Sci-fi'), (4, 'Dramat'), (2, 'Komedia'), (0, 'Inne')], null=True),
        ),
    ]
