# Generated by Django 3.1 on 2020-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bazaar_app', '0013_auto_20200822_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorrating',
            name='rate',
            field=models.IntegerField(choices=[(0, '☆☆☆☆☆☆☆☆☆☆'), (1, '★☆☆☆☆☆☆☆☆☆'), (2, '★★☆☆☆☆☆☆☆☆'), (3, '★★★☆☆☆☆☆☆☆'), (4, '★★★★☆☆☆☆☆☆'), (5, '★★★★★☆☆☆☆☆'), (6, '★★★★★★☆☆☆☆'), (7, '★★★★★★★☆☆☆'), (8, '★★★★★★★★☆☆'), (9, '★★★★★★★★★☆'), (10, '★★★★★★★★★★')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Horror'), (2, 'Komedia'), (5, 'Akcja'), (0, 'Inne'), (7, 'Animowany'), (6, 'Katastroficzny'), (8, 'Kryminalny'), (3, 'Sci-fi'), (4, 'Dramat')], null=True),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='rate',
            field=models.IntegerField(choices=[(0, '☆☆☆☆☆☆☆☆☆☆'), (1, '★☆☆☆☆☆☆☆☆☆'), (2, '★★☆☆☆☆☆☆☆☆'), (3, '★★★☆☆☆☆☆☆☆'), (4, '★★★★☆☆☆☆☆☆'), (5, '★★★★★☆☆☆☆☆'), (6, '★★★★★★☆☆☆☆'), (7, '★★★★★★★☆☆☆'), (8, '★★★★★★★★☆☆'), (9, '★★★★★★★★★☆'), (10, '★★★★★★★★★★')]),
        ),
    ]
